apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story
  template: 
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: barthilas/kub-data-demo:2
          env:
            - name: STORY_FOLDER
              # value: 'story'
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: folder
          volumeMounts:
            - mountPath: /app/story # path in container
              name: story-volume
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc
        # a bit like bind mount, more pod-independence. Share already existing data to pod.
          # hostPath:
          #   path: /data
          #   type: DirectoryOrCreate
          # emptyDir: {} # survives container restarts. Writing works, firs read fails. EmptyDir per Pod -> replicas > 1 fails, great for single replica.