FROM node:14-alpine

WORKDIR /app

ENTRYPOINT [ "npm" ]

# docker build -t node-util .
# docker run -it -v "C:\Users\snetivy\Desktop\Docker Udemy\utility-container\:/app"  node-util npm init 
# docker run -it -v "C:\Users\snetivy\Desktop\Docker Udemy\utility-container\:/app"  node-util init (with ENTRYPOINT)