apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels: #can be used for deletion
    group: example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: second-app
      tier: backend
    # matchExpression:
    #   - {key: app, operator: In, values: [second-app, first-app]}

  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-nodejs
          image: barthilas/kub-first-app:2
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 3
            initialDelaySeconds: 5
        # - name: ....
        #   image: ....