apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: barthilas/kub-demo-users:latest
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default" # Using DNS (kubectl get namespaces {after .})
              # value: "10.106.214.83" # pod to pod internal (kubectl get services), clumsy better solution above.
              # value: localhost # internal container to container communication in same pod. (not recommended having two containers inside the same pod, unless they are STRONGLY tied.)