apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: barthilas/kub-demo-users:latest
          env:
            - name: AUTH_ADDRESS
              value: localhost # internal container to container communication in same pod.
        - name: auth
          image: barthilas/kub-demo-auth:latest